//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CampusNavigation.rc
//
#define IDB_C7_C8_1                     8
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CAMPUSNAVIGATION_DIALOG     102
#define IDR_MAINFRAME                   128
#define IDB_MMAIN                       133
#define IDB_MRDS1SEL                    134
#define IDB_MRDS2SEL                    135
#define IDB_MRDS3SEL                    136
#define IDB_MROADMARK                   137
#define IDB_S1SELECTED                  138
#define IDB_S2SELECTED                  139
#define IDB_S3SELECTED                  140
#define IDB_SECTION1                    141
#define IDB_SECTION2                    142
#define IDB_SECTION3                    143
#define IDB_BITMAP1                     144
#define IDB_A11                         144
#define IDB_BITMAP2                     145
#define IDB_A1                          145
#define IDB_A2                          146
#define IDB_A3                          147
#define IDB_A4                          148
#define IDB_A5                          149
#define IDB_A6                          150
#define IDB_A7                          151
#define IDB_A8                          152
#define IDB_A9                          153
#define IDB_A10                         154
#define IDB_A41                         155
#define IDB_A42                         156
#define IDB_A43                         157
#define IDB_A44                         158
#define IDB_A45                         159
#define IDB_A46                         160
#define IDB_A47                         161
#define IDB_A48                         162
#define IDB_BUILDING1                   163
#define IDB_BITMAP4                     164
#define IDB_BUILDING2                   164
#define IDB_SHOPPING1                   166
#define IDB_BITMAP5                     167
#define IDB_SHOPPING2                   167
#define IDB_DLG1                        168
#define IDB_BITBMP25                    168
#define IDB_TUSHUGUANDLG1               169
#define IDB_BITMAP3                     172
#define IDB_TUSHUGUANDLG2               172
#define IDB_BITMAP6                     175
#define IDB_BITMAP7                     176
#define IDB_BITMAP8                     177
#define IDB_BITMAP9                     178
#define IDB_BITMAP10                    179
#define IDB_BITMAP11                    180
#define IDB_BITMAP12                    181
#define IDB_BITMAP13                    182
#define IDB_BITMAP14                    183
#define IDB_BITMAP15                    184
#define IDB_BITMAP16                    185
#define IDB_BITMAP17                    186
#define IDB_BITMAP18                    188
#define IDB_BITMAP19                    189
#define IDB_BITMAP20                    190
#define IDB_BITMAP21                    191
#define IDB_BITMAP22                    192
#define IDB_BITMAP23                    193
#define IDB_BITMAP24                    194
#define IDB_C0_RIGHT_HR2                195
#define IDB_BITMAP26                    196
#define IDB_BITMAP27                    197
#define IDB_BITMAP28                    198
#define IDB_BITMAP29                    199
#define IDB_BITMAP30                    200
#define IDB_BITMAP31                    201
#define IDB_BITMAP32                    202
#define IDB_BITMAP33                    203
#define IDB_C0_RIGHT_HR1                204
#define IDB_C0_RIGHT_HR3                206
#define IDB_C0_RIGHT_HR4                207
#define IDB_C0_RIGHT_HR5                208
#define IDB_BITMAP25                    209
#define IDB_STARTPOINT                  209
#define IDB_SOUTHDOOR_C0_1              210
#define IDB_SOUTHDOOR_C0_2              211
#define IDB_SOUTHDOOR_SONGJIAN_1        212
#define IDB_SOUTHDOOR_SONGJIAN_2        213
#define IDB_SOUTHDOOR_SONGJIAN_3        214
#define IDB_SOUTHDOOR_SONGJIAN_4        215
#define IDB_SOUTHDOOR_WEST_TECH_HOUSE_9 216
#define IDB_SOUTHDOOR_WEST_TECH_HOUSE_1 217
#define IDB_SOUTHDOOR_WEST_TECH_HOUSE_2 218
#define IDB_SOUTHDOOR_WEST_TECH_HOUSE_3 219
#define IDB_SOUTHDOOR_WEST_TECH_HOUSE_4 220
#define IDB_SOUTHDOOR_WEST_TECH_HOUSE_5 221
#define IDB_SOUTHDOOR_WEST_TECH_HOUSE_6 222
#define IDB_SOUTHDOOR_WEST_TECH_HOUSE_7 223
#define IDB_SOUTHDOOR_WEST_TECH_HOUSE_8 224
#define IDB_c0_c1_5                     230
#define IDB_c0_c1_4                     231
#define IDB_c0_c1_3                     232
#define IDB_c0_c1_2                     233
#define IDB_c0_c1_1                     234
#define IDB_C1_C2_1                     235
#define IDB_C1_C2_2                     236
#define IDB_C1_C2_3                     237
#define IDB_C2_C7_3                     238
#define IDB_C2_C7_2                     239
#define IDB_C2_C7_1                     240
#define IDB_C2_C7_4                     241
#define IDB_C2_LIBRARY_1                242
#define IDB_C2_LIBRARY_2                243
#define IDB_C2_LIBRARY_3                244
#define IDB_C7_C8_4                     245
#define IDB_BITIDB_C7_C8_1MAP35         246
#define IDB_C7_C8_3                     247
#define IDB_C7_C8_2                     248
#define IDB_LIBRARY_ONE_1               250
#define IDB_LIBRARY_ONE_2               251
#define IDB_LIBRARY_ONE_3               252
#define IDB_LIBRARY_ONE_4               253
#define IDB_LIBRARY_ONE_5               254
#define IDB_C8_N_1                      255
#define IDB_C8_N_2                      256
#define IDB_C8_N_3                      257
#define IDB_C8_N_14                     262
#define IDB_C8_N_13                     263
#define IDB_C8_N_12                     264
#define IDB_C8_N_11                     265
#define IDB_C8_N_10                     266
#define IDB_C8_N_9                      267
#define IDBIDB_C8_N_4_BITMAP40          268
#define IDB_C8_N_4_BITMAP40             268
#define IDB_C8_N_8                      269
#define IDB_C8_N_7                      270
#define IDB_C8_N_6                      271
#define IDB_C8_N_5                      272
#define IDB_C8_N_4                      273
#define IDB_C8_N_16                     275
#define IDB_C8_N_15                     276
#define IDB_SIGN_2                      288
#define IDB_SIGN_1                      289
#define IDB_BB_1                        291
#define IDB_BB_2                        292
#define IDB_BH_2                        293
#define IDB_BN_1                        294
#define IDB_BN_2                        295
#define IDB_BSONGJIAN_2                 297
#define IDB_BSONGJIAN_1                 298
#define IDB_BIT_B1                      301
#define IDB_BIT_B2                      302
#define IDB_BIT_H1                      303
#define IDB_BIT_H2                      304
#define IDB_BIT_N1                      305
#define IDB_BIT_SONGJIAN1               307
#define IDB_BIT_SONGJIAN2               308
#define IDB_BITMAP34                    311
#define IDB_BIT_N2                      313
#define IDB_BIT_SIGN_1                  316
#define IDB_BIT_SIGN_2                  317
#define IDB_BUILDING_A                  318
#define IDB_BUILDING_B                  319
#define IDB_BUILDING_C                  320
#define IDB_BUILDING_D                  321
#define IDB_BUILDING_G                  322
#define IDB_BUILDING_H                  323
#define IDB_BUILDING_M                  324
#define IDB_BUILDING_N                  325
#define IDB_DEPARTMENT1                 326
#define IDB_DEPARTMENT2                 327
#define IDB_DEPARTMENT3                 328
#define IDB_DEPARTMENT4                 329
#define IDB_DEPARTMENT5                 330
#define IDB_DEPARTMENT6                 331
#define IDB_DEPARTMENT7                 332
#define IDB_DEPARTMENT8                 333
#define IDB_DEPARTMENT9                 334
#define IDB_DEPARTMENT10                335
#define IDB_DLG2                        337
#define IDB_HOSPITAL                    338
#define IDB_ICBC                        339
#define IDB_LOVER                       340
#define IDB_SONGJIAN                    341
#define IDB_SOUTHDOOR                   342
#define IDB_TBUILDING_A                 343
#define IDB_TBUILDING_B                 344
#define IDB_TBUIL                       345
#define IDB_TEACHERHOM                  346
#define IDB_TEACHERHOME1                347
#define IDB_XUEYUAN                     348
#define IDB_XUEZI                       349
#define IDB_YOUXIA                      350
#define IDB_ZAOTANG                     351
#define IDB_ZUOSHANG                    352
#define IDB_ZUOXIA                      353
#define IDB_TBUILDING                   355
#define IDB_NORMALSENCE                 359
#define IDC_BUTTON1                     1000
#define IDC_BLOCKSEL                    1001
#define IDC_ROADMARK                    1002
#define IDC_BUILDINGMARK                1003
#define IDC_CHECK4                      1004
#define IDC_BUTTON7                     1004
#define IDC_CHECK5                      1005
#define IDC_SHOPPINGMARK                1005
#define IDC_EDIT1                       1006
#define IDC_CHECK6                      1007
#define IDC_DEPARTMARK                  1007
#define IDC_BUTTON2                     1008
#define IDC_BUTTON3                     1009
#define IDC_ENTERSENCE                  1009
#define IDC_BUTTON5                     1010
#define IDC_BUTTON6                     1011
#define IDC_BUTTON8                     1012
#define IDC_BUILDINGNAME                1013
#define IDC_DEPARTMENT                  1014
#define IDC_SHOPPING                    1015
#define IDC_BUTTON4                     1016
#define IDC_SHORTESTPATH                1016
#define IDC_COMBOBOXEX4                 1030
#define IDC_STATIC3                     1044
#define IDC_STATIC4                     1045
#define IDC_COMBO3                      1050
#define IDC_COMBO4                      1051
#define IDC_COMBO5                      1053
#define IDC_BUTTON9                     1054
#define IDC_BUTTON10                    1055
#define IDC_BUTTON11                    1056
#define IDC_COMBO1                      1057
#define IDC_BUTTON12                    1058
#define IDC_BUTTON13                    1059
#define IDC_STOPVISIT                   1059
#define IDC_BUTTON14                    1060
#define IDC_BUTTON15                    1061

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        360
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
